version: '3.8'

services:
  maker-job-watcher:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RPC_URL=${RPC_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - SEQUENCER_ADDRESS=${SEQUENCER_ADDRESS}
      - BLOCKS_TO_ANALYZE=${BLOCKS_TO_ANALYZE:-10}
      - NETWORK=${NETWORK:-0x0000000000000000000000000000000000000000000000000000000000000001}
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Local blockchain for testing (Ganache)
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    command: >
      ganache
      --host 0.0.0.0
      --port 8545
      --networkId 1337
      --accounts 10
      --deterministic
      --mnemonic "test test test test test test test test test test test junk"
    profiles:
      - testing

volumes:
  logs: